
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xzbugiyntpdthmfkhdbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6YnVnaXludHBkdGhtZmtoZGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjIzMzIsImV4cCI6MjA2MTgzODMzMn0.zpE5sDbSYa9RdHS0Dy2O7m1SXQkBP17juqMp0hZVkS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Using less strict typing to work with tables not in the schema
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
